import { asc, eq } from "drizzle-orm";
import { addWorkspaceMemberAction, updateWorkspaceMemberAction } from "@/app/actions/workspace";
import { db } from "@/lib/db";
import { requireMerchantWorkspace } from "@/lib/merchant-workspace";
import { users, workspaceMemberships } from "@/lib/schema";

const roleLabels = { OWNER: "Owner", ADMIN: "Admin", FINANCE: "Finance", STAFF: "Staff", MEMBER: "Member lama" };
const statusLabels = { INVITED: "Diundang", ACTIVE: "Aktif", SUSPENDED: "Ditangguhkan", REVOKED: "Dicabut" };

export default async function TeamPage({ searchParams }: { searchParams: Promise<{ error?: string; success?: string }> }) {
  const { workspace } = await requireMerchantWorkspace("workspace.members.manage");
  const { error, success } = await searchParams;
  const members = await db.select({ membership: workspaceMemberships, user: users }).from(workspaceMemberships)
    .innerJoin(users, eq(users.id, workspaceMemberships.userId))
    .where(eq(workspaceMemberships.workspaceId, workspace.id)).orderBy(asc(users.name));

  return <main className="app-main"><div className="shell"><div className="page-head"><div><span className="eyebrow">Workspace</span><h1 className="display" style={{ marginTop: 12 }}>Tim {workspace.name}</h1><p>Tambahkan pengguna yang sudah terdaftar, lalu atur peran dan status aksesnya.</p></div></div>{error && <p className="alert">{error}</p>}{success && <p className="alert alert-success">{success}</p>}<div className="two-col"><section className="panel"><div className="panel-head"><h2>Tambah anggota</h2></div><form className="form panel-form" action={addWorkspaceMemberAction}><div className="field"><label htmlFor="memberEmail">Email pengguna</label><input className="input" id="memberEmail" name="email" type="email" required placeholder="nama@email.com" /></div><div className="field"><label htmlFor="memberRole">Peran</label><select className="input" id="memberRole" name="role" defaultValue="STAFF"><option value="OWNER">Owner</option><option value="ADMIN">Admin</option><option value="FINANCE">Finance</option><option value="STAFF">Staff</option></select></div><button className="btn btn-primary" type="submit">Tambahkan ke workspace</button><small className="field-hint">Pengguna harus sudah memiliki akun Lajurin. Admin platform tidak dapat ditambahkan.</small></form></section><section className="panel"><div className="panel-head"><h2>Hak akses</h2></div><div className="stack"><p><strong>Owner</strong><br /><span className="muted">Seluruh pengaturan, anggota, dan keuangan.</span></p><p><strong>Admin</strong><br /><span className="muted">Operasional dan anggota, tanpa pengaturan billing.</span></p><p><strong>Finance</strong><br /><span className="muted">Laporan, tagihan, serta aktivitas keuangan.</span></p><p><strong>Staff</strong><br /><span className="muted">Akses operasional dasar.</span></p></div></section></div><section className="panel"><div className="panel-head"><h2>Anggota workspace</h2><span className="badge">{members.length}</span></div>{members.map(({ membership, user }) => <form className="finance-row" action={updateWorkspaceMemberAction.bind(null, membership.id)} key={membership.id}><div><strong>{user.name}</strong><small>{user.email} · {roleLabels[membership.role]} · {statusLabels[membership.status]}</small></div><div className="actions"><select className="input compact-input" name="role" defaultValue={membership.role === "MEMBER" ? "STAFF" : membership.role}><option value="OWNER">Owner</option><option value="ADMIN">Admin</option><option value="FINANCE">Finance</option><option value="STAFF">Staff</option></select><select className="input compact-input" name="status" defaultValue={membership.status === "INVITED" ? "ACTIVE" : membership.status}><option value="ACTIVE">Aktif</option><option value="SUSPENDED">Ditangguhkan</option><option value="REVOKED">Dicabut</option></select><button className="btn" type="submit">Simpan</button></div></form>)}</section></div></main>;
}
