import Link from "next/link";
import { ArrowRight, BookOpen, CreditCard, LayoutDashboard, MessageCircle } from "lucide-react";
import { Nav } from "@/components/nav";
import { Brand } from "@/components/brand";

export default function Home() {
  const steps = [["01","Buat produk","Isi judul, penawaran, harga, dan materi kursus."],["02","Terbitkan","Dapatkan halaman produk yang siap dibagikan."],["03","Terima pembayaran","Gunakan Xendit atau transfer bank dengan konfirmasi manual."],["04","Rawat member","Buka akses materi dan lanjutkan interaksi di komunitas."]];
  return <><Nav /><main><section className="hero shell"><span className="eyebrow">Platform jualan produk digital</span><h1 className="display">Dari ide menjadi pemasukan, lebih cepat.</h1><p>Buat halaman jualan, terima pembayaran, berikan akses kursus, dan bangun komunitas member. Semua dari dashboard yang sederhana.</p><div className="hero-actions"><Link className="btn btn-primary" href="/register">Buat produk pertama <ArrowRight size={17} /></Link><a className="btn" href="#cara-kerja">Lihat cara kerja</a></div><div className="trust-row"><span>✓ Transfer manual & payment gateway</span><span>✓ Dashboard sesuai peran</span><span>✓ Dibuat untuk Indonesia</span></div></section>
    <section className="section" id="fitur"><div className="shell"><div className="section-head"><span className="eyebrow">Satu tempat</span><h2 className="display">Fokus pada produkmu. Sistemnya biar kami urus.</h2><p>Alur penting untuk mulai menjual dan menjaga hubungan dengan member sudah tersambung.</p></div><div className="grid-4"><article className="feature-card"><div className="icon"><LayoutDashboard /></div><h3>Dashboard sesuai peran</h3><p>Admin, merchant, dan member mendapatkan ringkasan serta tindakan yang sesuai kebutuhannya.</p></article><article className="feature-card"><div className="icon"><CreditCard /></div><h3>Pembayaran fleksibel</h3><p>Gunakan Xendit atau transfer bank dengan unggah bukti dan persetujuan admin.</p></article><article className="feature-card"><div className="icon"><BookOpen /></div><h3>Kursus dan member area</h3><p>Akses materi aktif otomatis setelah pembayaran terkonfirmasi.</p></article><article className="feature-card"><div className="icon"><MessageCircle /></div><h3>Komunitas eksklusif</h3><p>Member berdiskusi melalui postingan dan komentar dalam ruang yang hanya bisa diakses pelanggan.</p></article></div></div></section>
    <section className="section section-dark" id="cara-kerja"><div className="shell"><div className="section-head"><span className="eyebrow">Alur sederhana</span><h2 className="display">Empat langkah menuju penjualan pertama.</h2><p>Lajurin menghilangkan pekerjaan teknis yang biasanya tersebar di banyak aplikasi.</p></div><div className="flow">{steps.map(([n,t,d]) => <article className="flow-step" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section></main><footer className="footer"><div className="shell" style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><Brand /><span>© 2026 Lajurin</span></div></footer></>;
}
