import Link from "next/link";
import { ArrowRight, BookOpen, CreditCard, LayoutTemplate } from "lucide-react";
import { Nav } from "@/components/nav";
import { Brand } from "@/components/brand";

export default function Home() {
  const steps = [["01","Buat produk","Isi judul, penawaran, harga, dan materi kursus."],["02","Terbitkan","Dapatkan halaman produk yang siap dibagikan."],["03","Terima pembayaran","Pembeli membayar melalui kanal yang tersedia di Xendit."],["04","Akses otomatis","Materi langsung muncul di akun member setelah lunas."]];
  return <><Nav /><main><section className="hero shell"><span className="eyebrow">Platform jualan produk digital</span><h1 className="display">Dari ide menjadi pemasukan, lebih cepat.</h1><p>Buat halaman jualan, terima pembayaran Xendit, dan berikan akses kursus secara otomatis. Semua dari satu dashboard yang sederhana.</p><div className="hero-actions"><Link className="btn btn-primary" href="/register">Buat produk pertama <ArrowRight size={17} /></Link><a className="btn" href="#cara-kerja">Lihat cara kerja</a></div><div className="trust-row"><span>✓ Tanpa kartu kredit</span><span>✓ Setup dalam hitungan menit</span><span>✓ Dibuat untuk Indonesia</span></div></section>
    <section className="section" id="fitur"><div className="shell"><div className="section-head"><span className="eyebrow">Satu tempat</span><h2 className="display">Fokus pada produkmu. Sistemnya biar kami urus.</h2><p>Alur penting untuk mulai menjual sudah tersambung sejak awal.</p></div><div className="grid-3"><article className="feature-card"><div className="icon"><LayoutTemplate /></div><h3>Halaman jualan siap pakai</h3><p>Tulis penawaran, tentukan harga, lalu terbitkan halaman produk tanpa menyentuh kode.</p></article><article className="feature-card"><div className="icon"><CreditCard /></div><h3>Checkout dengan Xendit</h3><p>Pembeli diarahkan ke checkout aman. Status pembayaran diperbarui otomatis melalui webhook.</p></article><article className="feature-card"><div className="icon"><BookOpen /></div><h3>Kursus dan member area</h3><p>Akses materi aktif otomatis setelah pembayaran terkonfirmasi.</p></article></div></div></section>
    <section className="section section-dark" id="cara-kerja"><div className="shell"><div className="section-head"><span className="eyebrow">Alur sederhana</span><h2 className="display">Empat langkah menuju penjualan pertama.</h2><p>Lajurin menghilangkan pekerjaan teknis yang biasanya tersebar di banyak aplikasi.</p></div><div className="flow">{steps.map(([n,t,d]) => <article className="flow-step" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section></main><footer className="footer"><div className="shell" style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><Brand /><span>© 2026 Lajurin</span></div></footer></>;
}
