import { asc, count, desc, eq } from "drizzle-orm";
import { createCommunityCommentAction, createCommunityPostAction, toggleCommunityPinAction } from "@/app/actions/community";
import { Nav } from "@/components/nav";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { formatDate } from "@/lib/order";
import { communityComments, communityPosts, enrollments, users } from "@/lib/schema";

export default async function CommunityPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const user = await requireUser();
  const { error } = await searchParams;
  if (user.role === "MEMBER") {
    const [{ value }] = await db.select({ value: count() }).from(enrollments).where(eq(enrollments.userId, user.id));
    if (!value) return <div className="app"><Nav app /><main className="app-main"><div className="shell"><section className="panel empty"><h1>Komunitas khusus member</h1><p>Akses komunitas terbuka setelah Anda memiliki minimal satu kursus aktif.</p></section></div></main></div>;
  }
  const posts = await db.select({ post: communityPosts, authorName: users.name, authorRole: users.role }).from(communityPosts).innerJoin(users, eq(communityPosts.authorId, users.id)).orderBy(desc(communityPosts.isPinned), desc(communityPosts.createdAt));
  const data = await Promise.all(posts.map(async (row) => ({ ...row, comments: await db.select({ comment: communityComments, authorName: users.name }).from(communityComments).innerJoin(users, eq(communityComments.authorId, users.id)).where(eq(communityComments.postId, row.post.id)).orderBy(asc(communityComments.createdAt)) })));
  return <div className="app"><Nav app /><main className="app-main"><div className="shell community-layout"><section><div className="page-head"><div><span className="eyebrow">Member eksklusif</span><h1 className="display" style={{marginTop:12}}>Komunitas Lajurin</h1><p>Diskusi, berbagi progres, dan tumbuh bersama.</p></div></div>{error && <p className="alert">{error}</p>}<div className="stack">{data.length ? data.map(({ post, authorName, authorRole, comments }) => <article className="panel community-post" key={post.id}><header><div><div className="post-author"><strong>{authorName}</strong><span className="badge">{authorRole}</span>{post.isPinned && <span className="badge badge-live">Disematkan</span>}</div><small>{formatDate(post.createdAt)}</small></div>{user.role !== "MEMBER" && <form action={toggleCommunityPinAction.bind(null, post.id)}><button className="btn btn-compact" type="submit">{post.isPinned ? "Lepas sematan" : "Sematkan"}</button></form>}</header><h2>{post.title}</h2><p className="post-content">{post.content}</p><div className="comments"><strong>{comments.length} komentar</strong>{comments.map(({ comment, authorName: commenter }) => <div className="comment" key={comment.id}><div><strong>{commenter}</strong><small>{formatDate(comment.createdAt)}</small></div><p>{comment.content}</p></div>)}<form className="comment-form" action={createCommunityCommentAction.bind(null, post.id)}><input className="input" name="content" required minLength={2} maxLength={1200} placeholder="Tulis komentar…" /><button className="btn" type="submit">Kirim</button></form></div></article>) : <section className="panel empty"><p>Belum ada postingan. Jadilah yang pertama berbagi.</p></section>}</div></section><aside className="panel form-panel community-compose"><div className="panel-head" style={{margin:-24,marginBottom:24}}><h2>Buat postingan</h2></div><form className="form" action={createCommunityPostAction}><div className="field"><label htmlFor="title">Judul</label><input className="input" id="title" name="title" required minLength={4} maxLength={140} /></div><div className="field"><label htmlFor="content">Isi postingan</label><textarea className="input" id="content" name="content" required minLength={10} maxLength={5000} placeholder="Bagikan pertanyaan, pengalaman, atau kabar terbaru…" /></div><button className="btn btn-primary" type="submit">Publikasikan</button></form></aside></div></main></div>;
}
