import { and, count, desc, eq, inArray, lt, sql } from "drizzle-orm";
import { Send } from "lucide-react";
import { sendBroadcastAction } from "@/app/actions/broadcast";
import { requireMerchant } from "@/lib/auth";
import { db } from "@/lib/db";
import { requireFeature } from "@/lib/feature-flags";
import { broadcastCampaigns, orders, products } from "@/lib/schema";

export default async function BroadcastsPage({ searchParams }: { searchParams: Promise<{ error?: string; success?: string }> }) {
  const merchant = await requireMerchant("manage");
  await requireFeature("CUSTOMER_BROADCASTS", merchant.id);
  const { error, success } = await searchParams;
  const [campaigns, [{ abandoned }], [{ customers }]] = await Promise.all([
    db.select().from(broadcastCampaigns).where(eq(broadcastCampaigns.merchantId, merchant.id)).orderBy(desc(broadcastCampaigns.createdAt)).limit(30),
    db.select({ abandoned: count() }).from(orders).innerJoin(products, eq(products.id, orders.productId)).where(and(eq(products.merchantId, merchant.id), inArray(orders.status, ["PENDING", "FAILED", "EXPIRED"]), lt(orders.createdAt, sql`now() - interval '30 minutes'`))),
    db.select({ customers: count() }).from(orders).innerJoin(products, eq(products.id, orders.productId)).where(and(eq(products.merchantId, merchant.id), eq(orders.status, "PAID"))),
  ]);
  return <main className="app-main"><div className="shell"><div className="page-head"><div><span className="eyebrow">Customer engagement</span><h1 className="display" style={{ marginTop: 12 }}>Broadcast & abandoned checkout</h1><p>Kirim kampanye ke pelanggan atau tindak lanjuti checkout yang belum selesai.</p></div></div>{error && <p className="alert">{error}</p>}{success && <p className="alert alert-success">{success}</p>}<div className="stats"><article className="stat"><span>Pelanggan berbayar</span><strong>{customers}</strong></article><article className="stat"><span>Checkout terbengkalai</span><strong>{abandoned}</strong></article></div><div className="two-col"><section className="panel form-panel"><div className="panel-head" style={{ margin: -24, marginBottom: 24 }}><h2>Buat broadcast</h2><Send size={19} /></div><form className="form" action={sendBroadcastAction}><div className="field"><label htmlFor="campaignName">Nama kampanye</label><input className="input" id="campaignName" name="name" required minLength={3} maxLength={100} /></div><div className="field"><label htmlFor="audience">Audience</label><select className="input" id="audience" name="audience"><option value="ALL_CUSTOMERS">Semua pelanggan berbayar</option><option value="ABANDONED_CHECKOUT">Checkout terbengkalai &gt; 30 menit</option></select></div><div className="two-field"><label className="check-field"><input type="checkbox" name="sendEmail" defaultChecked /><span>Email<small>Mailketing</small></span></label><label className="check-field"><input type="checkbox" name="sendWhatsapp" /><span>WhatsApp<small>StarSender</small></span></label></div><div className="field"><label htmlFor="subject">Subjek email</label><input className="input" id="subject" name="subject" maxLength={160} /></div><div className="field"><label htmlFor="message">Pesan</label><textarea className="input" id="message" name="message" required minLength={10} maxLength={3000} placeholder="Halo {nama}, lanjutkan akses ke {produk}..." /><small className="field-hint">Variabel: {"{nama}"} dan {"{produk}"}. Maksimal 100 penerima unik per pengiriman.</small></div><button className="btn btn-primary" type="submit">Kirim sekarang</button></form></section><section className="panel"><div className="panel-head"><h2>Riwayat kampanye</h2><span className="badge">{campaigns.length}</span></div>{campaigns.length ? campaigns.map((campaign) => <div className="finance-row" key={campaign.id}><div><strong>{campaign.name}</strong><small>{campaign.audience === "ALL_CUSTOMERS" ? "Pelanggan" : "Abandoned checkout"} · {campaign.status}</small></div><div className="broadcast-counts"><strong>{campaign.sentCount} terkirim</strong><small>{campaign.failedCount} gagal</small></div></div>) : <div className="empty"><p>Belum ada broadcast.</p></div>}</section></div></div></main>;
}
