/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import { and, desc, eq, ilike } from "drizzle-orm";
import { Nav } from "@/components/nav";
import { db } from "@/lib/db";
import { formatRupiah } from "@/lib/format";
import { merchantProfiles, productLandingPages, products } from "@/lib/schema";

export const metadata = { title: "Marketplace — Temukan Produk di Rizqhub", description: "Temukan kursus, produk digital, konsultasi, dan jasa dari merchant aktif di Rizqhub." };
export default async function MarketplacePage({ searchParams }: { searchParams: Promise<{ q?: string; type?: "COURSE" | "DIGITAL" | "SERVICE" }> }) {
  const { q, type } = await searchParams;
  const rows = await db.select({ product: products, merchant: merchantProfiles, landing: productLandingPages }).from(products).innerJoin(merchantProfiles, eq(merchantProfiles.userId, products.merchantId)).leftJoin(productLandingPages, eq(productLandingPages.productId, products.id)).where(and(eq(products.status, "PUBLISHED"), eq(merchantProfiles.status, "ACTIVE"), q ? ilike(products.name, `%${q.slice(0, 80)}%`) : undefined, type ? eq(products.type, type) : undefined)).orderBy(desc(products.updatedAt)).limit(60);
  return <><Nav /><main className="marketplace-page"><section className="marketplace-hero"><div className="shell"><span className="eyebrow">Marketplace Rizqhub</span><h1 className="display">Temukan produk dan keahlian yang membantu Anda maju.</h1><p>Kursus, file digital, konsultasi, dan jasa dari merchant aktif dalam satu katalog.</p><form className="marketplace-search"><input className="input" name="q" defaultValue={q ?? ""} placeholder="Cari produk atau layanan…" /><select className="input" name="type" defaultValue={type ?? ""}><option value="">Semua kategori</option><option value="COURSE">Kursus</option><option value="DIGITAL">Produk digital</option><option value="SERVICE">Jasa</option></select><button className="btn btn-primary">Cari</button></form></div></section><section className="section"><div className="shell"><div className="marketplace-result-head"><h2>{rows.length} penawaran ditemukan</h2></div><div className="marketplace-grid">{rows.map(({ product, merchant, landing }) => <Link className="marketplace-card" href={`/p/${product.slug}`} key={product.id}>{landing?.coverImageUrl ? <img src={landing.coverImageUrl} alt="" /> : <div className="marketplace-cover-placeholder"><span>{product.type === "COURSE" ? "KURSUS" : product.type === "DIGITAL" ? "DIGITAL" : "JASA"}</span></div>}<div><span className="badge">{product.type === "COURSE" ? "Kursus" : product.type === "DIGITAL" ? "Produk digital" : "Jasa"}</span><h2>{product.name}</h2><p>{product.headline}</p><small>{merchant.brandName}</small><strong>{formatRupiah(product.price)}</strong></div></Link>)}</div>{!rows.length && <div className="empty"><p>Belum ada produk yang sesuai. Coba kata kunci atau kategori lain.</p></div>}</div></section></main></>;
}
